apps/front/models.py
from exts import db
import shortuuid
from werkzeug.security import generate_password_hash,check_password_hash
import enum
from datetime import datetime


"""
(my_env) $ pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple shortuuid
"""


# pip install shortuuid

class GenderEnum(enum.Enum):
    MALE = 1
    FEMALE = 2
    SECRET = 3
    UNKNOW = 4

class FrontUser(db.Model):
    __tablename__ = 'front_user'
    id = db.Column(db.String(100),primary_key=True,default=shortuuid.uuid)
    telephone = db.Column(db.String(11),nullable=False,unique=True)
    username = db.Column(db.String(50),nullable=False)
    _password = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(50),unique=True)
    realname = db.Column(db.String(50))
    avatar = db.Column(db.String(100))
    signature = db.Column(db.String(100))
    gender = db.Column(db.Enum(GenderEnum),default=GenderEnum.UNKNOW)
    join_time = db.Column(db.DateTime,default=datetime.now)

    def __init__(self,*args,**kwargs):
        if "password" in kwargs:
            self.password = kwargs.get('password')
            kwargs.pop("password")
        super(FrontUser, self).__init__(*args,**kwargs)


    @property
    def password(self):
        return self._password

    @password.setter
    def password(self,newpwd):
        self._password = generate_password_hash(newpwd)

    def check_password(self,rawpwd):
        return check_password_hash(self._password,rawpwd)



#150讲

apps/common/views.py
from flask import  Blueprint

bp = Blueprint("common",__name__,url_prefix='/common')

@bp.route('/')
def index():
    return 'common  index'

apps/front/__init__.py
from .views import bp

apps/front/views.py
from flask import (
    Blueprint,
    views,
    render_template,
    make_response,
    Response,
    Flask,
    request

)
from utils.captcha import Captcha
from io import BytesIO
from PIL import Image, ImageFont, ImageDraw
from utils.CCPSDK import CCPRestSDK
from utils import restful
import config

bp = Blueprint("front", __name__)  # url_prefix='cms'表示一个前缀,这里不需要


@bp.route('/')
def index():
    return 'front index'


@bp.route('/captcha/')
def graph_captcha():
    text, image = Captcha.gene_graph_captcha()
    out = BytesIO()
    # with open("{}.png".format(image),'rb') as f:
    #     image = f.read()
    image.save(out, 'png')
    out.seek(0)
    resp = make_response(out.read())
    # print(resp)
    # resp = Response(resp,mimetype="image/png")
    # resp.context_type = 'image/png'
    resp.headers['Content-Type'] = 'image/jpg'

    return resp

@bp.route('/sms_captcha/')
def sms_captcha():
    telephone=request.args.get('telephone')
    if not telephone:
        return restful.params_error(message='请传入手机号码')
    accountSid = "8a216da86f17653b016f3b4046b218ab"
    accountToken = "ac156972012a43dab1782f1f89995ac9"
    appId = "8a216da86f17653b016f3b40471818b2"
    rest = CCPRestSDK.REST(accountSid, accountToken, appId)
    #下面要有产生随机的验证码函数
    captcha= Captcha.gene_text(number=4)
    result = rest.sendTemplateSMS(telephone, [captcha], "1")
    if result:
        return restful.success()
    else:
        return restful.params_error(message='短信验证码发送失败')



class SignupView(views.MethodView):
    def get(self):
        return render_template('front/front_signup.html')

##155课时(没有按照flask的来)，这里是测试代码
class SMSCodeView(views.MethodView):
    def get(self):
        #/smscode?tel=xxxxx
        telephone = request.args.get("tel")
        # telephone = request.values.get("tel")
        accountSid="8a216da86f17653b016f3b4046b218ab"
        accountToken = "ac156972012a43dab1782f1f89995ac9"
        appId ="8a216da86f17653b016f3b40471818b2"
        rest = CCPRestSDK.REST(accountSid,accountToken,appId)
        captcha = Captcha.gene_text(number=4)
        result = rest.sendTemplateSMS(telephone, [captcha], "1")
        # result= rest.sendTemplateSMS(telephone,["1234"],"1")
        print(result)
        return Response("success")






bp.add_url_rule('/signup/', view_func=SignupView.as_view('signup'))
bp.add_url_rule('/smscode/',view_func=SMSCodeView.as_view('smscode'))

templates/front/front_signbase.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/front/front_signup.html
{% from 'common/_macros.html' import static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>论坛注册</title>
     <script src="http://cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
    <link href="http://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="http://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="{{ static('common/zlparam.js') }}"></script>
     <script src="{{ static("common/zlajax.js") }}"></script>

 <link rel="stylesheet" href="{{ static("common/sweetalert/sweetalert.css") }}">

    <script src="{{ static("common/sweetalert/sweetalert.min.js")}}"></script>
    <script src="{{ static("common/sweetalert/zlalert.js")}}"></script>

    <script src="{{ static('front/js/front_signup.js') }}"></script>
    <link rel="stylesheet" href="{{ static('front/css/front_signup.css') }}">

</head>
<body>
<div class="outer-box">
<div class="logo-box">
    <a href="/">
        <img src="{{ static('common/images/h.png') }}" alt="">
    </a>
</div>
    <h2 class="page-title">账号登陆</h2>
    <div class="sign-box">
        <div class="form-group">
           <div class="input-group">
                <input type="text" class="form-control"
            name="telephone" placeholder="手机号码">
               <span class="input-group-btn">
                   <button id="sms-captcha-btn" class="btn btn-default">发送验证码</button>
               </span>
           </div>

        </div>
         <div class="form-group">
        <input type="text" class="form-control" name="sms_captcha" placeholder="短信验证码">
     </div>
    <div class="form-group">
        <input type="text" class="form-control" name="username" placeholder="用户名">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password1" placeholder="密码">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password2" placeholder="确认密码">
    </div>


<div class="form-group">
        <div class="input-group">
            <input type="text" class="form-control" name="graph_captcha" placeholder="图形验证码">
            <span class="input-group-addon captcha-addon">
{#                <img id="captcha-img" class="captcha-img" src="{{ url_for('common.graph_captcha') }}" alt="">#}
                <img id='captcha-img' class="captcha-img" src="{{ url_for('front.graph_captcha') }}" alt="">
            </span>
        </div>
    </div>
    <div class="form-group">
        <button class="btn btn-warning btn-block" id="submit-btn">立即注册</button>
    </div>



    </div>

</div>
</body>
</html>